import {StateGraph, StateSchema,START ,END,type GraphNode,} from "@langchain/langgraph"
import z from "zod"
import {mistralModel,cohereModel,geminiModel} from"./model.ai.js"
import {createAgent,HumanMessage,providerStrategy} from "langchain"
import {tavilyTool} from "./interner.services.js"
const state=new StateSchema({

    problem:z.string().default(""),
    route:z.enum(["WEB","NO_WEB"]).default("NO_WEB"),
    solution_1:z.string().default(""),
    solution_2:z.string().default(""),
    judge:z.object({
        solution_1_score:z.number().default(0),
        solution_2_score:z.number().default(0),
        solution_1_reasoning:z.string().default(""),
        solution_2_reasoning:z.string().default("")
    })
})
//RouterNode
const routerNode:GraphNode<typeof state>=async(state)=>{
    const router=createAgent({
        model:geminiModel,
        tools:[],
        responseFormat:providerStrategy(
            z.object({
                route:z.enum(["WEB","NO_WEB"]),
            })
        ),
       systemPrompt:`You are a routing AI.
       If the user,s question requires current information,
       latest news,weather,sports scores,stock prices,or anything from the internet,return WEB.

       Otherwise return NO_WEB.
       Return only the Routes
       `,
    })
    const response=await router.invoke({
        messages:[new HumanMessage(state.problem)],
    });
    return{
        route:response.structuredResponse.route
    }
}


const solutionNodeNoWeb: GraphNode<typeof state>=async(state)=>{
  const [mistralResponse,cohereResponse]=await Promise.all([
    mistralModel.invoke(state.problem),
    cohereModel.invoke(state.problem)
  ])
  return{
    solution_1:mistralResponse.text,
    solution_2:cohereResponse.text,
  }
}

//solution node with websearch
const mistralAgent=createAgent({
    model:mistralModel,
    tools:[tavilyTool],
})

const cohereAgent=createAgent({
model:cohereModel,
tools:[tavilyTool]
})

const solutionNodeWeb:GraphNode<typeof state>=async(state)=>{
    const [mistralResponse,cohereResponse]=await Promise.all([
        mistralAgent.invoke({
            messages:[
                new HumanMessage(state.problem),
            ],
        }),
        cohereAgent.invoke({
            messages:[new HumanMessage(state.problem)],
        }),
    ]);
    return{
        solution_1:mistralResponse.messages[mistralResponse.messages.length-1]?.text??"",

        solution_2:cohereResponse.messages[cohereResponse.messages.length-1]?.text??""
    }
}


const judgeNode: GraphNode <typeof state>=async(state)=>{
    const{problem , solution_1, solution_2}=state
 const judge=createAgent({
    model:geminiModel,
    tools:[],
    responseFormat:providerStrategy(z.object({
        solution_1_score:z.number().min(0).max(10),
        solution_2_score:z.number().min(0).max(10),
        solution_1_reasoning:z.string(),
        solution_2_reasoning:z.string()
    })),
    systemPrompt:`you are a judge tasked with evaluation two solutions generated by two diffrerent AI models to the following problem :${problem}.Please provide a score out of 0 to 10 from each solution,along with your reasoning of the scores `
 })
 const judgeResponse=await judge.invoke({
    messages:[
        new HumanMessage(`Problem: ${problem}
            solution_1: ${solution_1}
            solution_2: ${solution_2}
            Please evaluate the solution and provide scores and reasoning
            `)
    ]
 })
 const {
    solution_1_score,
    solution_2_score,
    solution_1_reasoning,
    solution_2_reasoning
 }=judgeResponse.structuredResponse
 return{
    judge:{
        solution_1_score,
        solution_2_score,
        solution_1_reasoning,
        solution_2_reasoning
    }
 }
}

const graph=new StateGraph(state)
.addNode("router",routerNode)
.addNode("solutionWeb",solutionNodeWeb)
.addNode("solutionNoWeb",solutionNodeNoWeb)
.addNode("judgee",judgeNode)
.addEdge(START,"router")
.addConditionalEdges(
    "router",
    (state)=>state.route,
    {
        WEB:"solutionWeb",
        NO_WEB:"solutionNoWeb"
    }
)
.addEdge("solutionWeb","judgee")
.addEdge("solutionNoWeb","judgee")
.addEdge("judgee",END)
.compile()




export default async function runGraph(problem:string){
    const result =await graph.invoke({
        problem:problem
    })
    return result
}