import {StateGraph, StateSchema,START ,END,type GraphNode,} from "@langchain/langgraph"
import z from "zod"
import {mistralModel,cohereModel,geminiModel} from"./model.ai.js"
import {createAgent,HumanMessage,providerStrategy} from "langchain"

const state=new StateSchema({

    problem:z.string().default(""),
    solution_1:z.string().default(""),
    solution_2:z.string().default(""),
    judge:z.object({
        solution_1_score:z.number().default(0),
        solution_2_score:z.number().default(0),
        solution_1_reasoning:z.string().default(""),
        solution_2_reasoning:z.string().default("")
    })
})

const solutionNode: GraphNode<typeof state>=async(state)=>{
  const [mistralResponse,cohereResponse]=await Promise.all([
    mistralModel.invoke(state.problem),
    cohereModel.invoke(state.problem)
  ])
  return{
    solution_1:mistralResponse.text,
    solution_2:cohereResponse.text,
  }
}

const judgeNode: GraphNode <typeof state>=async(state)=>{
    const{problem , solution_1, solution_2}=state
 const judge=createAgent({
    model:geminiModel,
    tools:[],
    responseFormat:providerStrategy(z.object({
        solution_1_score:z.number().min(0).max(10),
        solution_2_score:z.number().min(0).max(10),
        solution_1_reasoning:z.string(),
        solution_2_reasoning:z.string()
    })),
    systemPrompt:`you are a judge tasked with evaluation two solutions generated by two diffrerent AI models to the following problem :${problem}.Please provide a score out of 0 to 10 from each solution,along with your reasoning of the scores `
 })
 const judgeResponse=await judge.invoke({
    messages:[
        new HumanMessage(`Problem: ${problem}
            solution_1: ${solution_1}
            solution_2: ${solution_2}
            Please evaluate the solution and provide scores and reasoning
            `)
    ]
 })
 const {
    solution_1_score,
    solution_2_score,
    solution_1_reasoning,
    solution_2_reasoning
 }=judgeResponse.structuredResponse
 return{
    judge:{
        solution_1_score,
        solution_2_score,
        solution_1_reasoning,
        solution_2_reasoning
    }
 }
}

const graph=new StateGraph(state)
.addNode("solution",solutionNode)
.addNode("judgee",judgeNode)
.addEdge(START,"solution")
.addEdge("solution","judgee")
.addEdge("judgee",END)
.compile()




export default async function runGraph(problem:string){
    const result =await graph.invoke({
        problem:problem
    })
    return result
}